backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Image", name: "authorImage", widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "project"
    label: "Projects"
    folder: "src/pages/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Background Cover", name: "backgroundCover", widget: image}
      - {label: "Domain", name: "domain", widget: "string"}
      - {label: "Sub Title", name: "subTitle", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Tag Line", name: "tagLine", widget: "string"}
      - {label: "Project Logo with State", name: "projectLogoWithState", widget: image}
      - {label: Overview, name: overview, widget: list, fields: [{label: Text, name: text, widget: string}]}
      - {label: Scale, name: scale, widget: list, fields: [{label: Count, name: count, widget: string}, {label: Label, name: label, widget: string}]}
      - {label: "Center Banner", name: "centerBanner", widget: image}
      - {label: Approach, name: approach, widget: list, fields: [{label: Text, name: text, widget: string}]}
      - {label: Impact, name: impact, widget: list, fields: [{label: Count, name: count, widget: string}, {label: Label, name: label, widget: string}]}
      - {label: "Key Initiatives", name: keyInitiatives, widget: list, fields: [{label: "Image", name: "image", widget: image}, {label: Title, name: title, widget: string}, {label: Description, name: description, widget: object, fields: [{label: Text, name: text, widget: string}]}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Base Banner, name: baseBanner, widget: object, fields: [{label: "Title Lines", name: "titleLines", widget: list, fields: [{label: Text, name: text, widget: string}]}]}
          - {label: "Sub Banners", name: subBanners, widget: list, fields: [{label: "Title Lines", name: "titleLines", widget: list, fields: [{label: Text, name: text, widget: string}]}, {label: "Project Name", name: "projectName", widget: "string"}, {label: "Slides", name: "slides", widget: list, fields: [{label: "Image", name: image, widget: image}, {label: "Title", name: title, widget: string}]}]}
          - {label: "Second Section" ,name: secondSection, widget: object, fields: [{label: Title, name: title, widget: string}, {label: "Our Model", name: ourModel, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}, {label: Description, name: description, widget: list, fields: [{label: Sub Title, name: subTitle, widget: string}, {label: Text, name: text, widget: text}]}]}, {label: "Our Approach", name: ourApproach, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: list, fields: [{label: Sub Title, name: subTitle, widget: string}, {label: Text, name: text, widget: text}]}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/team/index.md"
        label: "Team Page"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: bannerImage, widget: image}
          - {label: "Sub Title", name: "subTitle", widget: "string"}
          - {label: Team, name: team, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Name, name: name, widget: text}, {label: Project, name: project, widget: text}, {label: Bio, name: bio, widget: text}, {label: "LinkedIn Profile", name: linkedInProfile, widget: text}]}
      - file: "src/pages/partners/index.md"
        label: "Partners Page"
        name: "partner"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partners-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: bannerImage, widget: image}
          - {label: "Sub Title", name: "subTitle", widget: "string"}
          - {label: "Partners Title", name: "partnerTitle", widget: text}
          - {label: "Tag Lines", name: titleLines, widget: list, fields: [{label: "Text", name: text, widget: "string"}]}
          - {label: Videos, name: "videos", widget: list, fields: [{label: "Video Url", name: videoUrl, widget: "string"}, {label: "Partner Name", name: partnerName, widget: "string"}, {label: Designation, name: designation, widget: "string"}]}
          - {label: Partners, name: partners, widget: list, fields: [{label: "Partner Image", name: image, widget: image}, {label: Description, name: description, widget: "text"}]}
      - file: "src/pages/careers/index.md"
        label: "Careers Page"
        name: "careers"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "careers-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: bannerImage, widget: image}
      - file: "src/pages/media/index.md"
        label: "Media Page"
        name: "media"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "media-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: bannerImage, widget: image}
          - {label: "Media Content", name: mediaContent, widget: list, fields: [{label: "Title", name: "title", widget: "string"},{label: "Project", name: "project", widget: "string"},{label: "Author", name: "author", widget: "string"},{label: "Link", name: "link", widget: "string"},{label: "Image", name: "image", widget: image},{label: "Date", name: "date", widget: "datetime"},{label: "Media House", name: "mediaHouse", widget: "string"}]}
