backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Image", name: "authorImage", widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "media"
    label: "Media"
    folder: "src/pages/media"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "media-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Image", name: "authorImage", widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "project"
    label: "Projects"
    folder: "src/pages/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Domain", name: "domain", widget: "string"}
      - {label: "Sub Title", name: "subTitle", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "Tag Line", name: "tagLine", widget: "string"}
      - {label: "Project Logo with State", name: "projectLogoWithState", widget: image}
      - {label: Overview, name: overview, widget: object, fields: [{label: Text, name: text, widget: string}]}
      - {label: Scale, name: scale, widget: object, fields: [{label: Count, name: count, widget: string}, {label: Label, name: label, widget: string}]}
      - {label: "Center Banner", name: "centerBanner", widget: image}
      - {label: Approach, name: approach, widget: object, fields: [{label: Text, name: text, widget: string}]}
      - {label: Impact, name: impact, widget: object, fields: [{label: Count, name: count, widget: string}, {label: Label, name: label, widget: string}]}
      - {label: "Key Initiatives", name: keyInitiatives, widget: object, fields: [{label: "Image", name: "image", widget: image}, {label: Title, name: title, widget: string}, {label: Description, name: description, widget: object, fields: [{label: Text, name: text, widget: string}]}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/team/index.md"
        label: "Team Page"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: bannerImage, widget: image}
          - {label: "Sub Title", name: "subTitle", widget: "string"}
          - {label: Team, name: team, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Name, name: name, widget: text}, {label: Project, name: project, widget: text}, {label: Bio, name: bio, widget: text}, {label: "LinkedIn Profile", name: linkedInProfile, widget: text}]}
      - file: "src/pages/partners/index.md"
        label: "Partners Page"
        name: "partner"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partners-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Banner Image", name: bannerImage, widget: image}
          - {label: "Sub Title", name: "subTitle", widget: "string"}
          - {label: "Partners Title", name: "partnerTitle", widget: text}
          - {label: "Tag Lines", name: titleLines, widget: list, fields: [{label: "Text", name: text, widget: "string"}]}
          - {label: Videos, name: "videos", widget: list, fields: [{label: "Video Url", name: videoUrl, widget: "string"}, {label: "Partner Name", name: partnerName, widget: "string"}, {label: Designation, name: designation, widget: "string"}]}
          - {label: Partners, name: partners, widget: list, fields: [{label: "Partner Image", name: image, widget: image}, {label: Description, name: description, widget: "text"}]}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
